import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navbar
    home: 'Home',
    contact: 'Contact',
    about: 'About',
    login: 'Log In',
    signup: 'Sign Up',
    adminPage: 'Admin Page',
    sellerPage: 'Seller Page',
    myAccount: 'My Account',
    welcome: 'Welcome',
    logout: 'Logout',
    
    // Login
    loginTitle: 'Log in to Exclusive',
    loginSubtitle: 'Enter your details below',
    emailOrPhone: 'Email or Phone Number',
    password: 'Password',
    loggingIn: 'Logging in...',
    logIn: 'Log In',
    dontHaveAccount: "Don't have an account?",
    
    // SignUp
    createAccount: 'Create an account',
    enterDetails: 'Enter your details below',
    firstName: 'First Name',
    lastName: 'Last Name',
    phoneNumber: 'Phone Number',
    email: 'Email',
    creatingAccount: 'Creating Account...',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have account?',
    
    // Home
    search: 'Search',
    categories: 'Categories',
    products: 'Products',
    loading: 'Loading...',
    noProducts: 'No products found',
    noCategories: 'No categories found',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    clearFilter: 'Clear Filter',
    // Product Detail
    description: 'Description',
    quantity: 'Quantity',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    items: 'items',
    max: 'Max',
    addToCart: 'Add to Cart',
    addMoreToCart: 'Add More to Cart',
    removeFromCart: 'Remove from Cart',
    addedToCart: 'Added to cart!',
    removedFromCart: 'Removed from cart!',
    inCart: 'In Cart',
    productCode: 'Product Code',
    category: 'Category',
    back: 'Back',
    backToHome: 'Back to Home',
    productNotFound: 'Product not found',
    
    // MyAccount
    myProfile: 'My Profile',
    updateProfile: 'Update Profile',
    personalInformation: 'Personal Information',
    passwordChanges: 'Password Changes',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully!',
    addressBook: 'Address Book',
    myPaymentOptions: 'My Payment Options',
    myOrders: 'My Orders',
    orderHistory: 'Order History',
    myReturns: 'My Returns',
    myCancellations: 'My Cancellations',
    myWishList: 'My WishList',
    noAddresses: 'No addresses saved yet.',
    noPaymentMethods: 'No payment methods saved yet.',
    noOrders: 'You have no orders yet.',
    noReturns: 'No returns found.',
    noCancellations: 'No cancellations found.',
    wishlistEmpty: 'Your wishlist is empty.',
    notSet: 'Not set',
    phoneCannotChange: 'Phone number cannot be changed',
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    orderDetails: 'Order Details',
    orderInformation: 'Order Information',
    orderItems: 'Order Items',
    viewDetails: 'View Details',
    status: 'Status',
    paymentStatus: 'Payment Status',
    paymentMethod: 'Payment Method',
    unitPrice: 'Unit Price',
    moreItems: 'more items',
    startShopping: 'Start Shopping',
    
    // Footer
    subscribe: 'Subscribe',
    getDiscount: 'Get 10% off your first order',
    enterEmail: 'Enter your email',
    support: 'Support',
    account: 'Account',
    quickLink: 'Quick Link',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms Of Use',
    faq: 'FAQ',
    copyright: 'Copyright Rimel 2022. All right reserved',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    totalProducts: 'Total Products',
    totalUsers: 'Total Users',
    totalOrders: 'Total Orders',
    revenue: 'Revenue',
    bannerManagement: 'Banner Management',
    topBannerText: 'Top Banner Text',
    bannerHint: 'This text will appear in the top banner across all pages',
    resetToDefault: 'Reset to Default',
    updateBanner: 'Update Banner',
    bannerUpdated: 'Banner text updated successfully!',
    bannerReset: 'Banner text reset to default!',
    quickActions: 'Quick Actions',
    manageProducts: 'Manage Products',
    manageUsers: 'Manage Users',
    viewOrders: 'View Orders',
    manageCategories: 'Manage Categories',
    manageSuppliers: 'Manage Suppliers',
    manageSellers: 'Manage Sellers',
    recentActivities: 'Recent Activities',
    noActivities: 'No recent activities',
    addProduct: 'Add Product',
    productName: 'Product Name',
    productDescription: 'Description',
    productPrice: 'Price',
    productSku: 'Product Code',
    productBarcode: 'Barcode',
    productCategory: 'Category',
    productImage: 'Product Image',
    selectCategory: 'Select Category',
    selectImage: 'Select Image',
    productAdded: 'Product added successfully!',
    productAddError: 'Failed to add product. Please try again.',
    addNewProduct: 'Add New Product',
    submit: 'Submit',
    creating: 'Creating...',
    
    // SuperAdmin
    superAdminDashboard: 'Super Admin Dashboard',
    superAdminPage: 'Super Admin Page',
    addNewRole: 'Add New Role',
    addNewPermission: 'Add New Permission',
    addNewCategory: 'Add New Category',
    addRole: 'Add Role',
    addPermission: 'Add Permission',
    addCategory: 'Add Category',
    roleName: 'Role Name',
    roleDescription: 'Role Description',
    permissionName: 'Permission Name',
    permissionDescription: 'Permission Description',
    permissionResource: 'Resource',
    permissionAction: 'Action',
    categoryName: 'Category Name',
    categoryDescription: 'Category Description',
    parentCategory: 'Parent Category',
    optional: 'Optional',
    noParentCategory: 'No Parent',
    permissions: 'Permissions',
    roleAdded: 'Role added successfully!',
    permissionAdded: 'Permission added successfully!',
    categoryAdded: 'Category added successfully!',
    roleAddError: 'Failed to add role. Please try again.',
    permissionAddError: 'Failed to add permission. Please try again.',
    categoryAddError: 'Failed to add category. Please try again.',
    
    // Contact
    getInTouch: 'Get in Touch',
    contactSubtitle: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    sendMessage: 'Send us a Message',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    subject: 'Subject',
    message: 'Message',
    sending: 'Sending...',
    sendMessageBtn: 'Send Message',
    messageSent: 'Thank you! Your message has been sent successfully. We\'ll get back to you soon.',
    contactInformation: 'Contact Information',
    address: 'Address',
    businessHours: 'Business Hours',
    followUs: 'Follow Us',
    mondayFriday: 'Monday - Friday: 9:00 AM - 6:00 PM',
    saturday: 'Saturday: 10:00 AM - 4:00 PM',
    sunday: 'Sunday: Closed',
    mapPlaceholder: 'Map Placeholder',
    addMapIntegration: 'Add your map integration here (Google Maps, etc.)',
    
    // About
    aboutExclusive: 'About Exclusive',
    aboutSubtitle: 'Your trusted partner in quality products and exceptional service',
    ourMission: 'Our Mission',
    ourVision: 'Our Vision',
    ourCoreValues: 'Our Core Values',
    ourTeam: 'Our Team',
    meetTeam: 'Meet the passionate people behind Exclusive',
    quality: 'Quality',
    customerFirst: 'Customer First',
    innovation: 'Innovation',
    sustainability: 'Sustainability',
    happyCustomers: 'Happy Customers',
    heroImagePlaceholder: 'Hero Image Placeholder',
    addHeroImage: 'Add your hero image here',
    missionImage: 'Mission Image',
    addMissionImage: 'Add your mission image here',
    visionImage: 'Vision Image',
    addVisionImage: 'Add your vision image here',
    teamMember: 'Team Member',
    positionRole: 'Position/Role',
    memberBio: 'Brief description about the team member and their contribution.',
    
    // Common
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    update: 'Update',
    close: 'Close',
    
    // Seller Registration
    becomeSeller: 'Become a Seller',
    becomeSellerSubtitle: 'Join our marketplace and start selling your products today!',
    sellerInformation: 'Seller Information',
    businessName: 'Business Name',
    enterBusinessName: 'Enter your business name (optional)',
    enterAddress: 'Enter your address',
    businessNameOptional: 'Optional - you can add this later',
    importantInformation: 'Important Information',
    sellerInfo1: 'You will be able to start selling immediately after registration.',
    sellerInfo2: 'Make sure all information provided is accurate.',
    submitApplication: 'Become a Seller',
    submitting: 'Submitting...',
    sellerRegistrationSuccess: 'Congratulations! You are now a seller. Please login again to continue.',
    sellerRegistrationSuccessLogin: 'You are now a seller! Please login again with your new seller role.',
    sellerRegistrationError: 'Failed to register as seller. Please try again.',
    fillRequiredFields: 'Please fill in all required fields.',
  },
  uz: {
    // Navbar
    home: 'Bosh sahifa',
    contact: 'Aloqa',
    about: 'Biz haqimizda',
    login: 'Kirish',
    signup: "Ro'yxatdan o'tish",
    adminPage: 'Admin sahifa',
    sellerPage: 'Sotuvchi sahifa',
    myAccount: 'Mening hisobim',
    welcome: 'Xush kelibsiz',
    logout: 'Chiqish',
    
    // Login
    loginTitle: "Exclusive'ga kirish",
    loginSubtitle: 'Quyidagi ma\'lumotlarni kiriting',
    emailOrPhone: 'Email yoki Telefon raqami',
    password: 'Parol',
    loggingIn: 'Kirilmoqda...',
    logIn: 'Kirish',
    dontHaveAccount: 'Hisobingiz yo\'qmi?',
    
    // SignUp
    createAccount: 'Hisob yaratish',
    enterDetails: 'Quyidagi ma\'lumotlarni kiriting',
    firstName: 'Ism',
    lastName: 'Familiya',
    phoneNumber: 'Telefon raqami',
    email: 'Email',
    creatingAccount: 'Hisob yaratilmoqda...',
    createAccountBtn: 'Hisob yaratish',
    alreadyHaveAccount: 'Allaqachon hisobingiz bormi?',
    
    // Home
    search: 'Qidirish',
    categories: 'Kategoriyalar',
    products: 'Mahsulotlar',
    loading: 'Yuklanmoqda...',
    noProducts: 'Mahsulot topilmadi',
    noCategories: 'Kategoriya topilmadi',
    previous: 'Oldingi',
    next: 'Keyingi',
    page: 'Sahifa',
    of: '/',
    clearFilter: 'Filterni tozalash',
    // Product Detail
    description: 'Tavsif',
    quantity: 'Miqdor',
    inStock: 'Omborda',
    outOfStock: 'Omborda yo\'q',
    items: 'dona',
    max: 'Maks',
    addToCart: 'Savatchaga qo\'shish',
    addMoreToCart: 'Yana qo\'shish',
    removeFromCart: 'Savatchadan olib tashlash',
    addedToCart: 'Savatchaga qo\'shildi!',
    removedFromCart: 'Savatchadan olib tashlandi!',
    inCart: 'Savatchada',
    productCode: 'Mahsulot kodi',
    category: 'Kategoriya',
    back: 'Orqaga',
    backToHome: 'Bosh sahifaga qaytish',
    productNotFound: 'Mahsulot topilmadi',
    
    // MyAccount
    myProfile: 'Mening profilim',
    updateProfile: 'Profilni yangilash',
    personalInformation: 'Shaxsiy ma\'lumotlar',
    passwordChanges: 'Parol o\'zgarishlari',
    currentPassword: 'Joriy parol',
    newPassword: 'Yangi parol',
    confirmPassword: 'Yangi parolni tasdiqlash',
    cancel: 'Bekor qilish',
    saveChanges: 'O\'zgarishlarni saqlash',
    saving: 'Saqlanmoqda...',
    profileUpdated: 'Profil muvaffaqiyatli yangilandi!',
    addressBook: 'Manzillar kitobi',
    myPaymentOptions: 'To\'lov usullarim',
    myOrders: 'Mening buyurtmalarim',
    orderHistory: 'Buyurtmalar tarixi',
    myReturns: 'Mening qaytarishlarim',
    myCancellations: 'Mening bekor qilishlarim',
    myWishList: 'Mening xohishlar ro\'yxatim',
    noAddresses: 'Hali manzil saqlanmagan.',
    noPaymentMethods: 'Hali to\'lov usuli saqlanmagan.',
    noOrders: 'Sizda hali buyurtmalar yo\'q.',
    orderNumber: 'Buyurtma raqami',
    orderDate: 'Buyurtma sanasi',
    orderDetails: 'Buyurtma tafsilotlari',
    orderInformation: 'Buyurtma ma\'lumotlari',
    orderItems: 'Buyurtma mahsulotlari',
    viewDetails: 'Tafsilotlarni ko\'rish',
    status: 'Holat',
    paymentStatus: 'To\'lov holati',
    paymentMethod: 'To\'lov usuli',
    unitPrice: 'Bitta narx',
    moreItems: 'yana mahsulotlar',
    startShopping: 'Xarid qilishni boshlash',
    noReturns: 'Qaytarish topilmadi.',
    noCancellations: 'Bekor qilish topilmadi.',
    wishlistEmpty: 'Xohishlar ro\'yxatingiz bo\'sh.',
    notSet: 'O\'rnatilmagan',
    phoneCannotChange: 'Telefon raqamini o\'zgartirib bo\'lmaydi',
    
    // Footer
    subscribe: 'Obuna bo\'lish',
    getDiscount: 'Birinchi buyurtmangizda 10% chegirma oling',
    enterEmail: 'Email kiriting',
    support: 'Yordam',
    account: 'Hisob',
    quickLink: 'Tezkor havolalar',
    privacyPolicy: 'Maxfiylik siyosati',
    termsOfUse: 'Foydalanish shartlari',
    faq: 'Savol-Javob',
    copyright: 'Mualliflik huquqi Rimel 2022. Barcha huquqlar himoyalangan',
    
    // Admin
    adminDashboard: 'Admin boshqaruv paneli',
    totalProducts: 'Jami mahsulotlar',
    totalUsers: 'Jami foydalanuvchilar',
    totalOrders: 'Jami buyurtmalar',
    revenue: 'Daromad',
    bannerManagement: 'Banner boshqaruvi',
    topBannerText: 'Yuqori banner matni',
    bannerHint: 'Bu matn barcha sahifalardagi yuqori bannerda ko\'rinadi',
    resetToDefault: 'Standartga qaytarish',
    updateBanner: 'Bannerni yangilash',
    bannerUpdated: 'Banner matni muvaffaqiyatli yangilandi!',
    bannerReset: 'Banner matni standartga qaytarildi!',
    quickActions: 'Tezkor harakatlar',
    manageProducts: 'Mahsulotlarni boshqarish',
    manageUsers: 'Foydalanuvchilarni boshqarish',
    viewOrders: 'Buyurtmalarni ko\'rish',
    manageCategories: 'Kategoriyalarni boshqarish',
    manageSuppliers: 'Yetkazib beruvchilarni boshqarish',
    manageSellers: 'Sotuvchilarni boshqarish',
    recentActivities: 'So\'nggi faoliyatlar',
    noActivities: 'So\'nggi faoliyatlar yo\'q',
    addProduct: 'Mahsulot qo\'shish',
    productName: 'Mahsulot nomi',
    productDescription: 'Tavsif',
    productPrice: 'Narx',
    productSku: 'Mahsulot kodi',
    productBarcode: 'Barkod',
    productCategory: 'Kategoriya',
    productImage: 'Mahsulot rasmi',
    selectCategory: 'Kategoriyani tanlang',
    selectImage: 'Rasm tanlang',
    productAdded: 'Mahsulot muvaffaqiyatli qo\'shildi!',
    productAddError: 'Mahsulot qo\'shishda xatolik. Iltimos, qayta urinib ko\'ring.',
    addNewProduct: 'Yangi mahsulot qo\'shish',
    submit: 'Yuborish',
    creating: 'Yaratilmoqda...',
    
    // SuperAdmin
    superAdminDashboard: 'Super Admin boshqaruv paneli',
    superAdminPage: 'Super Admin sahifa',
    addNewRole: 'Yangi rol qo\'shish',
    addNewPermission: 'Yangi ruxsat qo\'shish',
    addNewCategory: 'Yangi kategoriya qo\'shish',
    addRole: 'Rol qo\'shish',
    addPermission: 'Ruxsat qo\'shish',
    addCategory: 'Kategoriya qo\'shish',
    roleName: 'Rol nomi',
    roleDescription: 'Rol tavsifi',
    permissionName: 'Ruxsat nomi',
    permissionDescription: 'Ruxsat tavsifi',
    permissionResource: 'Resurs',
    permissionAction: 'Harakat',
    categoryName: 'Kategoriya nomi',
    categoryDescription: 'Kategoriya tavsifi',
    parentCategory: 'Ota kategoriya',
    optional: 'Ixtiyoriy',
    noParentCategory: 'Ota kategoriya yo\'q',
    permissions: 'Ruxsatlar',
    roleAdded: 'Rol muvaffaqiyatli qo\'shildi!',
    permissionAdded: 'Ruxsat muvaffaqiyatli qo\'shildi!',
    categoryAdded: 'Kategoriya muvaffaqiyatli qo\'shildi!',
    roleAddError: 'Rol qo\'shib bo\'lmadi. Iltimos, qayta urinib ko\'ring.',
    permissionAddError: 'Ruxsat qo\'shib bo\'lmadi. Iltimos, qayta urinib ko\'ring.',
    categoryAddError: 'Kategoriya qo\'shib bo\'lmadi. Iltimos, qayta urinib ko\'ring.',
    
    // Contact
    getInTouch: 'Bog\'lanish',
    contactSubtitle: 'Biz sizdan xabar olishni xohlaymiz. Xabaringizni yuboring va biz imkon qadar tezroq javob beramiz.',
    sendMessage: 'Xabar yuborish',
    fullName: 'To\'liq ism',
    emailAddress: 'Email manzil',
    subject: 'Mavzu',
    message: 'Xabar',
    sending: 'Yuborilmoqda...',
    sendMessageBtn: 'Xabar yuborish',
    messageSent: 'Rahmat! Xabaringiz muvaffaqiyatli yuborildi. Tez orada javob beramiz.',
    contactInformation: 'Aloqa ma\'lumotlari',
    address: 'Manzil',
    businessHours: 'Ish vaqti',
    followUs: 'Bizni kuzatib boring',
    mondayFriday: 'Dushanba - Juma: 9:00 - 18:00',
    saturday: 'Shanba: 10:00 - 16:00',
    sunday: 'Yakshanba: Yopiq',
    mapPlaceholder: 'Xarita',
    addMapIntegration: 'Xarita integratsiyasini qo\'shing (Google Maps, va boshqalar)',
    
    // About
    aboutExclusive: 'Exclusive haqida',
    aboutSubtitle: 'Sifatli mahsulotlar va ajoyib xizmatlarda ishonchli hamkoringiz',
    ourMission: 'Bizning missiyamiz',
    ourVision: 'Bizning ko\'zlagan maqsadimiz',
    ourCoreValues: 'Asosiy qadriyatlarimiz',
    ourTeam: 'Bizning jamoamiz',
    meetTeam: 'Exclusive orqasidagi ishtiyoqli odamlar bilan tanishing',
    quality: 'Sifat',
    customerFirst: 'Mijoz birinchi',
    innovation: 'Innovatsiya',
    sustainability: 'Barqarorlik',
    happyCustomers: 'Mamnun mijozlar',
    heroImagePlaceholder: 'Asosiy rasm',
    addHeroImage: 'Asosiy rasmingizni qo\'shing',
    missionImage: 'Missiya rasmi',
    addMissionImage: 'Missiya rasmingizni qo\'shing',
    visionImage: 'Ko\'zlagan maqsad rasmi',
    addVisionImage: 'Ko\'zlagan maqsad rasmingizni qo\'shing',
    teamMember: 'Jamoa a\'zosi',
    positionRole: 'Lavozim/Rol',
    memberBio: 'Jamoa a\'zosi va uning hissasi haqida qisqacha tavsif.',
    
    // Common
    edit: 'Tahrirlash',
    delete: 'O\'chirish',
    add: 'Qo\'shish',
    update: 'Yangilash',
    close: 'Yopish',
    
    // Seller Registration
    becomeSeller: 'Sotuvchi bo\'lish',
    becomeSellerSubtitle: 'Bizning bozorga qo\'shiling va bugundan boshlab mahsulotlaringizni sotishni boshlang!',
    sellerInformation: 'Sotuvchi ma\'lumotlari',
    businessName: 'Biznes nomi',
    enterBusinessName: 'Biznes nomingizni kiriting (ixtiyoriy)',
    enterAddress: 'Manzilingizni kiriting',
    businessNameOptional: 'Ixtiyoriy - keyinroq qo\'shishingiz mumkin',
    importantInformation: 'Muhim ma\'lumot',
    sellerInfo1: 'Ro\'yxatdan o\'tgandan so\'ng darhol sotishni boshlashingiz mumkin.',
    sellerInfo2: 'Barcha ma\'lumotlar to\'g\'ri bo\'lishiga ishonch hosil qiling.',
    submitApplication: 'Sotuvchi bo\'lish',
    submitting: 'Yuborilmoqda...',
    sellerRegistrationSuccess: 'Tabriklaymiz! Endi siz sotuvchisiz. Davom etish uchun qayta kirishingiz kerak.',
    sellerRegistrationSuccessLogin: 'Siz endi sotuvchisiz! Yangi sotuvchi roli bilan qayta kirishingiz kerak.',
    sellerRegistrationError: 'Sotuvchi sifatida ro\'yxatdan o\'tib bo\'lmadi. Iltimos, qayta urinib ko\'ring.',
    fillRequiredFields: 'Iltimos, barcha majburiy maydonlarni to\'ldiring.',
  },
  ru: {
    // Navbar
    home: 'Главная',
    contact: 'Контакты',
    about: 'О нас',
    login: 'Войти',
    signup: 'Регистрация',
    adminPage: 'Страница администратора',
    sellerPage: 'Страница продавца',
    myAccount: 'Мой аккаунт',
    welcome: 'Добро пожаловать',
    logout: 'Выйти',
    
    // Login
    loginTitle: 'Войти в Exclusive',
    loginSubtitle: 'Введите свои данные ниже',
    emailOrPhone: 'Email или номер телефона',
    password: 'Пароль',
    loggingIn: 'Вход...',
    logIn: 'Войти',
    dontHaveAccount: 'Нет аккаунта?',
    
    // SignUp
    createAccount: 'Создать аккаунт',
    enterDetails: 'Введите свои данные ниже',
    firstName: 'Имя',
    lastName: 'Фамилия',
    phoneNumber: 'Номер телефона',
    email: 'Email',
    creatingAccount: 'Создание аккаунта...',
    createAccountBtn: 'Создать аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    
    // Home
    search: 'Поиск',
    categories: 'Категории',
    products: 'Товары',
    loading: 'Загрузка...',
    noProducts: 'Товары не найдены',
    noCategories: 'Категории не найдены',
    previous: 'Предыдущая',
    next: 'Следующая',
    page: 'Страница',
    of: 'из',
    clearFilter: 'Очистить фильтр',
    // Product Detail
    description: 'Описание',
    quantity: 'Количество',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    items: 'шт',
    max: 'Макс',
    addToCart: 'Добавить в корзину',
    addMoreToCart: 'Добавить еще',
    removeFromCart: 'Удалить из корзины',
    addedToCart: 'Добавлено в корзину!',
    removedFromCart: 'Удалено из корзины!',
    inCart: 'В корзине',
    productCode: 'Код товара',
    category: 'Категория',
    back: 'Назад',
    backToHome: 'Вернуться на главную',
    productNotFound: 'Товар не найден',
    
    // MyAccount
    myProfile: 'Мой профиль',
    updateProfile: 'Обновить профиль',
    personalInformation: 'Личная информация',
    passwordChanges: 'Изменение пароля',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите новый пароль',
    cancel: 'Отмена',
    saveChanges: 'Сохранить изменения',
    saving: 'Сохранение...',
    profileUpdated: 'Профиль успешно обновлен!',
    addressBook: 'Адресная книга',
    myPaymentOptions: 'Мои способы оплаты',
    myOrders: 'Мои заказы',
    orderHistory: 'История заказов',
    myReturns: 'Мои возвраты',
    myCancellations: 'Мои отмены',
    myWishList: 'Мой список желаний',
    noAddresses: 'Адреса еще не сохранены.',
    noPaymentMethods: 'Способы оплаты еще не сохранены.',
    noOrders: 'У вас пока нет заказов.',
    orderNumber: 'Номер заказа',
    orderDate: 'Дата заказа',
    orderDetails: 'Детали заказа',
    orderInformation: 'Информация о заказе',
    orderItems: 'Товары в заказе',
    viewDetails: 'Просмотреть детали',
    status: 'Статус',
    paymentStatus: 'Статус оплаты',
    paymentMethod: 'Способ оплаты',
    unitPrice: 'Цена за единицу',
    moreItems: 'еще товары',
    startShopping: 'Начать покупки',
    noReturns: 'Возвраты не найдены.',
    noCancellations: 'Отмены не найдены.',
    wishlistEmpty: 'Ваш список желаний пуст.',
    notSet: 'Не установлено',
    phoneCannotChange: 'Номер телефона нельзя изменить',
    
    // Footer
    subscribe: 'Подписаться',
    getDiscount: 'Получите 10% скидку на первый заказ',
    enterEmail: 'Введите ваш email',
    support: 'Поддержка',
    account: 'Аккаунт',
    quickLink: 'Быстрые ссылки',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfUse: 'Условия использования',
    faq: 'FAQ',
    copyright: 'Авторские права Rimel 2022. Все права защищены',
    
    // Admin
    adminDashboard: 'Панель администратора',
    totalProducts: 'Всего товаров',
    totalUsers: 'Всего пользователей',
    totalOrders: 'Всего заказов',
    revenue: 'Доход',
    bannerManagement: 'Управление баннером',
    topBannerText: 'Текст верхнего баннера',
    bannerHint: 'Этот текст будет отображаться в верхнем баннере на всех страницах',
    resetToDefault: 'Сбросить по умолчанию',
    updateBanner: 'Обновить баннер',
    bannerUpdated: 'Текст баннера успешно обновлен!',
    bannerReset: 'Текст баннера сброшен по умолчанию!',
    quickActions: 'Быстрые действия',
    manageProducts: 'Управление товарами',
    manageUsers: 'Управление пользователями',
    viewOrders: 'Просмотр заказов',
    manageCategories: 'Управление категориями',
    manageSuppliers: 'Управление поставщиками',
    manageSellers: 'Управление продавцами',
    recentActivities: 'Последняя активность',
    noActivities: 'Нет последней активности',
    addProduct: 'Добавить товар',
    productName: 'Название товара',
    productDescription: 'Описание',
    productPrice: 'Цена',
    productSku: 'Код товара',
    productBarcode: 'Штрих-код',
    productCategory: 'Категория',
    productImage: 'Изображение товара',
    selectCategory: 'Выберите категорию',
    selectImage: 'Выберите изображение',
    productAdded: 'Товар успешно добавлен!',
    productAddError: 'Не удалось добавить товар. Пожалуйста, попробуйте снова.',
    addNewProduct: 'Добавить новый товар',
    submit: 'Отправить',
    creating: 'Создание...',
    
    // SuperAdmin
    superAdminDashboard: 'Панель супер администратора',
    superAdminPage: 'Страница супер администратора',
    addNewRole: 'Добавить новую роль',
    addNewPermission: 'Добавить новое разрешение',
    addNewCategory: 'Добавить новую категорию',
    addRole: 'Добавить роль',
    addPermission: 'Добавить разрешение',
    addCategory: 'Добавить категорию',
    roleName: 'Название роли',
    roleDescription: 'Описание роли',
    permissionName: 'Название разрешения',
    permissionDescription: 'Описание разрешения',
    permissionResource: 'Ресурс',
    permissionAction: 'Действие',
    categoryName: 'Название категории',
    categoryDescription: 'Описание категории',
    parentCategory: 'Родительская категория',
    optional: 'Необязательно',
    noParentCategory: 'Нет родительской категории',
    permissions: 'Разрешения',
    roleAdded: 'Роль успешно добавлена!',
    permissionAdded: 'Разрешение успешно добавлено!',
    categoryAdded: 'Категория успешно добавлена!',
    roleAddError: 'Не удалось добавить роль. Пожалуйста, попробуйте снова.',
    permissionAddError: 'Не удалось добавить разрешение. Пожалуйста, попробуйте снова.',
    categoryAddError: 'Не удалось добавить категорию. Пожалуйста, попробуйте снова.',
    
    // Contact
    getInTouch: 'Связаться с нами',
    contactSubtitle: 'Мы будем рады услышать от вас. Отправьте нам сообщение, и мы ответим как можно скорее.',
    sendMessage: 'Отправить сообщение',
    fullName: 'Полное имя',
    emailAddress: 'Адрес электронной почты',
    subject: 'Тема',
    message: 'Сообщение',
    sending: 'Отправка...',
    sendMessageBtn: 'Отправить сообщение',
    messageSent: 'Спасибо! Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.',
    contactInformation: 'Контактная информация',
    address: 'Адрес',
    businessHours: 'Часы работы',
    followUs: 'Следите за нами',
    mondayFriday: 'Понедельник - Пятница: 9:00 - 18:00',
    saturday: 'Суббота: 10:00 - 16:00',
    sunday: 'Воскресенье: Закрыто',
    mapPlaceholder: 'Карта',
    addMapIntegration: 'Добавьте интеграцию карты здесь (Google Maps и т.д.)',
    
    // About
    aboutExclusive: 'О Exclusive',
    aboutSubtitle: 'Ваш надежный партнер в качественных продуктах и исключительном сервисе',
    ourMission: 'Наша миссия',
    ourVision: 'Наше видение',
    ourCoreValues: 'Наши основные ценности',
    ourTeam: 'Наша команда',
    meetTeam: 'Познакомьтесь с увлеченными людьми, стоящими за Exclusive',
    quality: 'Качество',
    customerFirst: 'Клиент прежде всего',
    innovation: 'Инновации',
    sustainability: 'Устойчивость',
    happyCustomers: 'Довольные клиенты',
    heroImagePlaceholder: 'Главное изображение',
    addHeroImage: 'Добавьте ваше главное изображение здесь',
    missionImage: 'Изображение миссии',
    addMissionImage: 'Добавьте изображение миссии здесь',
    visionImage: 'Изображение видения',
    addVisionImage: 'Добавьте изображение видения здесь',
    teamMember: 'Член команды',
    positionRole: 'Должность/Роль',
    memberBio: 'Краткое описание члена команды и его вклада.',
    
    // Common
    edit: 'Редактировать',
    delete: 'Удалить',
    add: 'Добавить',
    update: 'Обновить',
    close: 'Закрыть',
    
    // Seller Registration
    becomeSeller: 'Стать продавцом',
    becomeSellerSubtitle: 'Присоединяйтесь к нашей торговой площадке и начните продавать свои товары уже сегодня!',
    sellerInformation: 'Информация о продавце',
    businessName: 'Название бизнеса',
    enterBusinessName: 'Введите название вашего бизнеса (необязательно)',
    enterAddress: 'Введите ваш адрес',
    businessNameOptional: 'Необязательно - можно добавить позже',
    importantInformation: 'Важная информация',
    sellerInfo1: 'Вы сможете начать продавать сразу после регистрации.',
    sellerInfo2: 'Убедитесь, что вся предоставленная информация точна.',
    submitApplication: 'Стать продавцом',
    submitting: 'Отправка...',
    sellerRegistrationSuccess: 'Поздравляем! Теперь вы продавец. Пожалуйста, войдите снова, чтобы продолжить.',
    sellerRegistrationSuccessLogin: 'Теперь вы продавец! Пожалуйста, войдите снова с новой ролью продавца.',
    sellerRegistrationError: 'Не удалось зарегистрироваться как продавец. Пожалуйста, попробуйте снова.',
    fillRequiredFields: 'Пожалуйста, заполните все обязательные поля.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    // Dispatch event for other components
    window.dispatchEvent(new Event('languageChanged'));
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const value = {
    language,
    changeLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
